
exports.seed = function(knex, Promise) {
  return knex('recipe_ingredients').truncate()
    .then(function () {
      return knex('recipe_ingredients').insert([
        {id: 1, recipe_id: 1, ingredient_id: 1, quantity: '2'},
        {id: 2, recipe_id: 1, ingredient_id: 2, quantity: '1 tsp'},
        {id: 3, recipe_id: 1, ingredient_id: 3, quantity: '1'},
        {id: 4, recipe_id: 2, ingredient_id: 3, quantity: '1'},
        {id: 5, recipe_id: 2, ingredient_id: 4, quantity: '2'},
        {id: 6, recipe_id: 2, ingredient_id: 8, quantity: '1'},
        {id: 7, recipe_id: 3, ingredient_id: 1, quantity: '2'},
        {id: 8, recipe_id: 3, ingredient_id: 3, quantity: '1'},
        {id: 9, recipe_id: 3, ingredient_id: 9, quantity: '2'},
        {id: 10, recipe_id: 3, ingredient_id: 8, quantity: '1'},
        {id: 11, recipe_id: 3, ingredient_id: 16, quantity: '3'},
        {id: 12, recipe_id: 4, ingredient_id: 7, quantity: '3'},
        {id: 13, recipe_id: 4, ingredient_id: 8, quantity: '1'},
        {id: 14, recipe_id: 4, ingredient_id: 9, quantity: '1'},
        {id: 15, recipe_id: 4, ingredient_id: 10, quantity: '1'},
        {id: 16, recipe_id: 4, ingredient_id: 13, quantity: '1'},
        {id: 17, recipe_id: 4, ingredient_id: 11, quantity: '1 tsp'},
        {id: 18, recipe_id: 4, ingredient_id: 12, quantity: '2 tsp'},
        {id: 19, recipe_id: 5, ingredient_id: 1, quantity: '4'},
        {id: 20, recipe_id: 5, ingredient_id: 9, quantity: '1'},
        {id: 21, recipe_id: 5, ingredient_id: 8, quantity: '2'},
        {id: 22, recipe_id: 5, ingredient_id: 11, quantity: '1 tsp'},
        {id: 23, recipe_id: 5, ingredient_id: 12, quantity: '3 tsp'},
        {id: 24, recipe_id: 6, ingredient_id: 1, quantity: '8'},
        {id: 25, recipe_id: 6, ingredient_id: 6, quantity: '200 ml'},
        {id: 26, recipe_id: 6, ingredient_id: 9, quantity: '2'},
        {id: 27, recipe_id: 6, ingredient_id: 10, quantity: '1 tsp'},
        {id: 28, recipe_id: 7, ingredient_id: 13, quantity: '10'},
        {id: 29, recipe_id: 7, ingredient_id: 8, quantity: '1'},
        {id: 30, recipe_id: 7, ingredient_id: 9, quantity: '1'},
        {id: 31, recipe_id: 7, ingredient_id: 14, quantity: '1'},
        {id: 32, recipe_id: 7, ingredient_id: 4, quantity: '1'},
        {id: 33, recipe_id: 7, ingredient_id: 6, quantity: '150 ml'},
        {id: 34, recipe_id: 7, ingredient_id: 12, quantity: '4'},
        {id: 35, recipe_id: 8, ingredient_id: 13, quantity: '1'},
        {id: 36, recipe_id: 8, ingredient_id: 6, quantity: '100 ml'},
        {id: 37, recipe_id: 8, ingredient_id: 8, quantity: '1'},
        {id: 38, recipe_id: 8, ingredient_id: 9, quantity: '1'},
        {id: 39, recipe_id: 8, ingredient_id: 14, quantity: '2'},
        {id: 40, recipe_id: 8, ingredient_id: 12, quantity: '1 tsp'},
        {id: 41, recipe_id: 9, ingredient_id: 13, quantity: '4'},
        {id: 42, recipe_id: 9, ingredient_id: 15, quantity: '6'},
        {id: 43, recipe_id: 9, ingredient_id: 16, quantity: '400g'},
        {id: 44, recipe_id: 9, ingredient_id: 5, quantity: '1 tsp'},
      ]);
    });
};